spring:
  config:
    activate:
      on-profile: local
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}"

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8081

keycloak:
  server-url: "${KEYCLOAK_SERVER_URL}"
  realm: "${KEYCLOAK_REALM}"
  client-id: "${KEYCLOAK_CLIENT_ID}"
  client-secret: "${KEYCLOAK_CLIENT_SECRET}"
  admin:
    username: "${KEYCLOAK_ADMIN_USERNAME}"
    password: "${KEYCLOAK_ADMIN_PASSWORD}"
    realm: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}"
  instance:
    prefer-ip-address: true

internal:
  user-service-url: "${USER_SERVICE}"
  account-service-url: "${ACCOUNT_SERVICE}"
  customer-service-url: "${CUSTOMER_SERVICE}"
  gateway-service-url: "${GATEWAY_SERVICE}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  security:
    enabled: false
  prometheus:
    metrics:
      export:
        enabled: true

